name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Set up Docker Buildx for advanced builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up builds
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Log in to Docker Hub or GitHub Container Registry (Optional)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build and tag Docker image
      run: |
        docker buildx build \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new \
          --tag my-image-name:${{ github.sha }} \
          --tag my-image-name:latest \
          --file Dockerfile \
    #      --push . # Optional: only if you want to push the image to a registry

    # Push the Docker image (optional if already pushed with build)
    # Uncomment if you are not using --push in the previous build step.
    # - name: Push the Docker image
    #   run: docker push my-image-name:${{ github.sha }}

    # Save the new cache to make future builds faster
    - name: Save Docker layer cache
      if: success()
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-new
        key: ${{ runner.os }}-buildx-${{ github.sha }}
